version: '3.4'
services:
  database:
    build:
      context: .
      args:
        DOWNLOAD_USER: ${DOWNLOAD_USER}
        DOWNLOAD_PASSWORD: ${DOWNLOAD_PASSWORD}
      dockerfile: docker/Dockerfile.database
    container_name: piba-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pibapass
      MYSQL_DATABASE: piba
      MYSQL_USER: piba
      MYSQL_PASSWORD: pibapass
    volumes:
      - piba-database-data:/var/lib/mysql
    networks:
      piba-network:
        ipv4_address: 172.30.0.10
    healthcheck:
      test: mysqladmin -p$$MYSQL_ROOT_PASSWORD ping || exit 1
      start_period: 30s
      interval: 2s
      timeout: 4s
      retries: 3

  backend:
    build:
      context: .
      args:
        FRONTEND_IP: ${FRONTEND_IP:-172.30.0.30}
        BACKEND_IP: ${BACKEND_IP:-172.30.0.20}
        BACKEND_HTTP_PORT: ${BACKEND_HTTP_PORT:-8080}
        BACKEND_REPOSITORY: ${BACKEND_REPOSITORY:-snapshots}
        BACKEND_VERSION: ${BACKEND_VERSION:-0.1.0-SNAPSHOT}
        BACKEND_PACKAGE_VERSION: ${BACKEND_PACKAGE_VERSION:-0.1.0-20220613.072625-13}
      dockerfile: docker/Dockerfile.backend
    container_name: piba-backend
    ports:
      - "${BACKEND_HTTP_PORT:-8080}:8080"
      - "${BACKEND_ADMIN_PORT:-9990}:9990"
    restart: always
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - piba-files:/piba-files
    networks:
      piba-network:
        ipv4_address: 172.30.0.20
  frontend:
    build:
      context: .
      args:
        BACKEND_IP: ${BACKEND_IP:-172.30.0.20}
        BACKEND_HTTP_PORT: ${BACKEND_HTTP_PORT:-8080}
        FRONTEND_REPOSITORY: ${FRONTEND_REPOSITORY:-snapshots}
        FRONTEND_VERSION: ${FRONTEND_VERSION:-0.1.0-alpha.312}
      dockerfile: docker/Dockerfile.frontend
    container_name: piba-frontend
    ports:
      - "${FRONTEND_HTTP_PORT:-80}:80"
    restart: always
    depends_on:
      - database
      - backend
    networks:
      piba-network:
        ipv4_address: 172.30.0.30
volumes:
  piba-database-data:
  piba-files:
    external: true
networks:
  piba-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.30.0.0/16
